### PR TITLE
Show "Play" button in Ink file inspector when it located in Streaming…

### PR DESCRIPTION
**Pull request by DMinsky**
…Assets folder

I'm not sure, that this is good solution for #23 but it's very simple. It show Play button in Ink inspector for ink files located in StreamingAssets folder.

### CODE REVIEW

**Comment by tomkail** [comment]
So I'll admit I'm not especially familiar with StreamingAssets, but I'm probably not going to merge this for a few reasons (sorry!).
- This won't work if you move the JSON file outside the same directory as the ink file, and fixing that would be a nightmare since you can't easily track the file.
- Writing ink files in StreamingAssets is a little dubious since it'll mean that the actual ink file will be included in builds, which is wasteful, but also allows people to easily copy your ink. Neither case is a big deal, but I'd probably suggest only having the JSON file in StreamingAssets; maybe as a pre-compile step, in which case the problem goes away.
- I'd rather not add code for what I'd consider a niche case. At the same time, I'm super interested to hear how and why you're using StreamingAssets! If there are some nice advantages to it, we might have a look ourselves!

**Comment by DMinsky** [comment]
Thank Tom,

I absolutely understand your point and I agree with them. It was just my solution, for my particular case, so it's ok ;)

**Comment by tomkail** [comment]
Cheers! Can I ask why you're using StreamedAssets? I'm pretty curious!

**Comment by DMinsky** [comment]
We want to make the game "moddable" as much as possible. So, modifying ink files by people is exactly what we need. We put all sprites and settings files into StreamingAssets. So, people can easily modify the game.

**Pull request closed without merging**
